# Generated by Django 4.1.4 on 2022-12-19 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_death_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Borrowed')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 6, 31, 29, 253670)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_out',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 6, 31, 29, 253670)),
        ),
    ]
