# Generated by Django 4.1.4 on 2022-12-19 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_birth_death_date_author_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 6, 32, 27, 782322)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_out',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 6, 32, 27, 782322)),
        ),
    ]
