# Generated by Django 4.1.4 on 2022-12-19 20:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_book_title_alter_loan_date_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_due',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 21, 24, 57, 845230)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_out',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 21, 24, 57, 845230)),
        ),
    ]
